insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020101011','LAND (COSTS)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020201011','LAND IMPROVEMENTS (COSTS)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2021001011','LEASEHOLD IMPROVEMENTS (COST)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020301011','BUILDING AND STRUCTURE (COSTS)','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020303011','BUILDING IMPROVEMENTS (COSTS)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2021901011','POWER PLANTS (COST)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2021601011','TRANSMISSION & DISTRIBUTION EQUIPMENT (COST)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2021701011','SUBSTATION EQUIPMENT (COST)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2022101011','CONSUMERS (KWH) METERS (COST)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020701011','COMMUNICATION EQUIPMENT (COST)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020601011','COMPUTER EQUIPMENT (COSTS)','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2080301011','SOFTWARE AND LICENSES__','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020401011','MOTOR VEHICLES - OPERATIONAL (COSTS)','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2028001011','TOOLS (COST)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020901011','FURNITURE & FIXTURES (COST)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020801011','OFFICE EQUIPMENT (COST)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2028007011','MISCELLANEOUS EQUIPMENT (COST)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2028080902','FIXED ASSETS (CLEARING)','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2021201011','MACHINERY (COST)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2021303011','COOLING TOWER (COST)_','PPE COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020201012','ACCUMULATED DEPRECIATION - LAND IMPROVEMENTS (COSTS)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2021001012','ACCUMULATED DEPRECIATION - LEASEHOLD IMPROVEMENTS (COST)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020301012','ACCUMULATED DEPRECIATION - BUILDING AND STRUCTURE (COSTS)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020303012','ACCUMULATED DEPRECIATION - BUILDING IMPROVEMENTS (COSTS)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2021901012','ACCUMULATED DEPRECIATION - POWER PLANTS (COST)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2021601012','ACCUMULATED DEPRECIATION - TRANSMISSION & DISTRIBUTION EQUIPMENT (COST)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2021701012','ACCUMULATED DEPRECIATION - SUBSTATION EQUIPMENT (COST)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2022101012','ACCUMULATED DEPRECIATION - CONSUMERS (KWH) METERS (COST)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020701012','ACCUMULATED DEPRECIATION - COMMUNICATION EQUIPMENT (COST)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020601012','ACCUMULATED DEPRECIATION - COMPUTER EQUIPMENT (COSTS)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2080301012','ACCUM. AMORT. - SOFTWARE AND LICENSES','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020401012','ACCUMULATED DEPRECIATION - MOTOR VEHICLES - OPERATIONAL (COSTS)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2028001012','ACCUMULATED DEPRECIATION - TOOLS (COST)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020901012','ACCUMULATED DEPRECIATION - FURNITURE & FIXTURES (COST)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2020801012','ACCUMULATED DEPRECIATION - OFFICE EQUIPMENT (COST)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2028007012','ACCUMULATED DEPRECIATION - MISCELLANEOUS EQUIPMENT (COST)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2021201012','ACCUMULATED DEPRECIATION - MACHINERY (COST)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','2021303012','ACCUMULATED DEPRECIATION - COOLING TOWER (COST)','ACCUM. DEPRECIATION - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901101','GA- DEPRECIATION - COST - LAND IMPROVEMENTS','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901110','GA- DEPRECIATION - COST - LEASEHOLD IMPROVEMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901102','GA- DEPRECIATION - COST - BUILDING AND STRUCTURE','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901103','GA- DEPRECIATION - COST - BUILDING IMPROVEMENTS','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901119','GA- DEPRECIATION - COST - POWER PLANTS','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901117','GA- DEPRECIATION - COST - TRANSMISSION & DISTRIBUTION EQUIPMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901118','GA- DEPRECIATION - COST - SUBSTATION EQUIPMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901122','GA- DEPRECIATION - COST - CONSUMERS (KWH) METERS','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901107','GA- DEPRECIATION - COST - COMMUNICATION EQUIPMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901106','GA- DEPRECIATION - COST - COMPUTER EQUIPMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090201102','GA- AMORTIZATION - COST - SOFTWARE AND LICENSES','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901104','GA- DEPRECIATION - COST - MOTOR VEHICLES - OPERATIONAL','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901123','GA- DEPRECIATION - COST - TOOLS','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901109','GA- DEPRECIATION - COST - FURNITURE AND FIXTURES','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901108','GA- DEPRECIATION - COST - OFFICE EQUIPMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901126','GA- DEPRECIATION - COST - MISCELLANEOUS EQUIPMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901112','GA- DEPRECIATION - COST - MACHINERY','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7090901114','GA- DEPRECIATION - COST - COOLING TOWER','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401101','OM- DEPRECIATION - COST - LAND IMPROVEMENTS','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401110','OM- DEPRECIATION - COST - LEASEHOLD IMPROVEMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401102','OM- DEPRECIATION - COST - BUILDING AND STRUCTURE','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401103','OM- DEPRECIATION - COST - BUILDING IMPROVEMENTS','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401130','OM- DEPRECIATION - COST - POWER PLANTS','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401128','OM- DEPRECIATION - COST - TRANSMISSION & DISTRIBUTION EQUIPMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401129','OM- DEPRECIATION - COST - SUBSTATION EQUIPMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401131','OM- DEPRECIATION - COST - CONSUMERS (KWH) METERS','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401107','OM- DEPRECIATION - COST - COMMUNICATION EQUIPMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401106','OM- DEPRECIATION - COST - COMPUTER EQUIPMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060101104','OM- AMORTIZATION - SOFTWARE AND LICENSES','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401104','OM- DEPRECIATION - COST - MOTOR VEHICLES','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401116','OM- DEPRECIATION - COST - TOOLS','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401109','OM- DEPRECIATION - COST - FURNITURE AND FIXTURES','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401108','OM- DEPRECIATION - COST - OFFICE EQUIPMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401120','OM- DEPRECIATION - COST - MISCELLANEOUS EQUIPMENT','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','7060401111','OM- DEPRECIATION - COST - MACHINERY','DEPRECIATION EXP. - COST');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('02', 'EXPENSE CODES','8301001101','GAIN(LOSS) ON SALE(DISPOSAL) OF PROPERTY, PLANT AND EQUIPMENT_','GAIN/LOSS ON SALE OF PPE');

commit;