set define off;

insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888201','GA- OUTSIDE SERVICES - OTHERS - DU - BILL DELIVERY','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888202','GA- OUTSIDE SERVICES - OTHERS - DU - BILL PRINTING','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888203','GA- OUTSIDE SERVICES - OTHERS - DU - COLLECTING AGENTS','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888204','GA- OUTSIDE SERVICES - OTHERS - DU - CUSTOMER REPRESENTATIVE','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888205','GA- OUTSIDE SERVICES - OTHERS - DU - DISCONNECTION','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888206','GA- OUTSIDE SERVICES - OTHERS - DU - ELECTRICAL MATERIALS TESTING','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888207','GA- OUTSIDE SERVICES - OTHERS - DU - EMERGENCY','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888208','GA- OUTSIDE SERVICES - OTHERS - DU - GENERAL','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888209','GA- OUTSIDE SERVICES - OTHERS - DU - LINE HAZARD SURVEY','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888210','GA- OUTSIDE SERVICES - OTHERS - DU - LINE TRIMMING','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888211','GA- OUTSIDE SERVICES - OTHERS - DU - LOAD CENTERING METER','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888212','GA- OUTSIDE SERVICES - OTHERS - DU - MESSENGERIAL','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888213','GA- OUTSIDE SERVICES - OTHERS - DU - METER CALIBRATION','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888214','GA- OUTSIDE SERVICES - OTHERS - DU - METER CONNECTION','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888215','GA- OUTSIDE SERVICES - OTHERS - DU - METER INSPECTION','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888216','GA- OUTSIDE SERVICES - OTHERS - DU - METER READING','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888217','GA- OUTSIDE SERVICES - OTHERS - DU - METER TESTING AND REPAIR','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888218','GA- OUTSIDE SERVICES - OTHERS - DU - NETWORK ASSETS INVENTORY','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888219','GA- OUTSIDE SERVICES - OTHERS - DU - POWER METERING REHAB','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888220','GA- OUTSIDE SERVICES - OTHERS - DU - PSION MAINTENANCE','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888221','GA- OUTSIDE SERVICES - OTHERS - DU - SERVICE RECONNECTION','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888222','GA- OUTSIDE SERVICES - OTHERS - DU - SOLAR','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888223','GA- OUTSIDE SERVICES - OTHERS - DU - SPECIAL OPERATIONS','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888224','GA- OUTSIDE SERVICES - OTHERS - DU - STREETLIGHT MAINTENANCE','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888225','GA- OUTSIDE SERVICES - OTHERS - DU - SUBSTATION MAINTENANCE','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888226','GA- OUTSIDE SERVICES - OTHERS - DU - SURVEY','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888227','GA- OUTSIDE SERVICES - OTHERS - DU - SYSTEM DEVELOPMENT','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888228','GA- OUTSIDE SERVICES - OTHERS - DU - TELLERING','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888229','GA- OUTSIDE SERVICES - OTHERS - DU - WAREHOUSE HELPER','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888230','GA- OUTSIDE SERVICES - OTHERS - DU - T&D LINE EQUIPMENT','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888231','GA- OUTSIDE SERVICES - OTHERS - DU - COMMUNICATION EQUIPMENT','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888232','GA- OUTSIDE SERVICES - OTHERS - DU - NETWORK ASSET REMOVAL','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888233','GA- OUTSIDE SERVICES - OTHERS - DU - POWER PLANT','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888234','GA- OUTSIDE SERVICES - OTHERS - DU - LINE SCANNING','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888235','GA- OUTSIDE SERVICES - OTHERS - DU - CALL TAKING AND DISPATCHING','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888236','GA- OUTSIDE SERVICES - OTHERS - DU - CALL CENTER SERVICE REPRESENTATIVE','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7091888237','GA- OUTSIDE SERVICES - OTHERS - DU - CCTV AND ACCESS CONTROL MAINTENANCE','OUTSIDE SERVICES');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401101','GA- REPAIRS & MAINT. - LAND IMPROVEMENTS','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401102','GA- REPAIRS & MAINT. - BUILDING AND STRUCTURE','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401103','GA- REPAIRS & MAINT. - BUILDING IMPROVEMENTS','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401104','GA- REPAIRS & MAINT. - MOTOR VEHICLES','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401105','GA- REPAIRS & MAINT. - MOTOR VEHICLES - MOTORBIKE','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401106','GA- REPAIRS & MAINT. - MOTOR VEHICLES - NON DEDUCTIBLE','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401107','GA- REPAIRS & MAINT. - COMPUTER EQUIPMENT','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401108','GA- REPAIRS & MAINT. - COMMUNICATION EQUIPMENT','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401109','GA- REPAIRS & MAINT. - OFFICE EQUIPMENT','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401110','GA- REPAIRS & MAINT. - FURNITURE & FIXTURES','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401111','GA- REPAIRS & MAINT. - LEASEHOLD IMPROVEMENTS','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401112','GA- REPAIRS & MAINT. - MACHINERY','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401113','GA- REPAIRS & MAINT. - ELECTRICAL EQUIPMENT','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401117','GA- REPAIRS & MAINT. - TRANSMISSION & DISTRIBUTION EQUIPMENT','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401118','GA- REPAIRS & MAINT. - SUBSTATION EQUIPMENT','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401119','GA- REPAIRS & MAINT. - POWER PLANTS','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401121','GA- REPAIRS & MAINT. - CONSUMERS (KWH) METERS','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401122','GA- REPAIRS & MAINT. - TOOLS & OTHER EQUIPMENT','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401125','GA- REPAIRS & MAINT. - MISCELLANEOUS EQUIPMENT','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401127','GA- REPAIRS & MAINT. - STREETLIGHT','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401128','GA- REPAIRS & MAINT. - LINE CLEARING','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092401130','GA- REPAIRS & MAINT. - COMPUTER EQUIPMENT SOFTWARE','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7092488881','GA- REPAIRS & MAINT. - OTHERS','REPAIRS & MAINT.');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7093001104','GA - TRANS & TRAVEL - FUEL/GASOLINE','TRANSPO & TRAVEL');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7093001105','GA - TRANS & TRAVEL - FUEL/GASOLINE - MOTORBIKE','TRANSPO & TRAVEL');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7093001109','GA - TRANS & TRAVEL - PARTS & LABOR','TRANSPO & TRAVEL');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7093001110','GA - TRANS & TRAVEL - PARTS & LABOR - MOTORBIKE','TRANSPO & TRAVEL');
insert into sa_rule_key (plant, rule_id, key_name, key_desc, key_value) values ('01', 'EXPENSE CODES','7093088801','GA - TRANS & TRAVEL - OTHERS','TRANSPO & TRAVEL');

commit;