--------------------------------------------------------
--  DDL for Table COLLECTION_BATCHES_TMP
--------------------------------------------------------

  CREATE TABLE "CISADM_APPS"."COLLECTION_BATCHES_TMP" 
   (	"HDR_ID" NUMBER, 
	"BATCH_NO" NUMBER(15,0), 
	"SITE_CODE" VARCHAR2(20 BYTE), 
	"BOOTH" VARCHAR2(2 BYTE), 
	"TELLER" VARCHAR2(30 BYTE), 
	"MODE_OF_ENTRY" VARCHAR2(12 BYTE) DEFAULT 'ON-LINE', 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_ON" DATE, 
	"REMITTED_BY" VARCHAR2(30 BYTE), 
	"REMITTED_ON" DATE, 
	"TRANSMITTED_BY" VARCHAR2(30 BYTE), 
	"TRANSMITTED_ON" DATE, 
	"OFFLINE_OR_DATE" DATE, 
	"OR_COUNT" NUMBER DEFAULT 0, 
	"REQUESTED_LT_MIN" NUMBER(2,0), 
	"GRANTED_LT_MIN" NUMBER(2,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CISTS_DATA01" ;
--------------------------------------------------------
--  DDL for Index COLLECTION_BATCHES_TMP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CISADM_APPS"."COLLECTION_BATCHES_TMP_PK" ON "CISADM_APPS"."COLLECTION_BATCHES_TMP" ("BATCH_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CISTS_DATA01" ;
--------------------------------------------------------
--  Constraints for Table COLLECTION_BATCHES_TMP
--------------------------------------------------------

  ALTER TABLE "CISADM_APPS"."COLLECTION_BATCHES_TMP" MODIFY ("HDR_ID" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."COLLECTION_BATCHES_TMP" MODIFY ("BATCH_NO" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."COLLECTION_BATCHES_TMP" MODIFY ("SITE_CODE" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."COLLECTION_BATCHES_TMP" MODIFY ("BOOTH" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."COLLECTION_BATCHES_TMP" MODIFY ("TELLER" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."COLLECTION_BATCHES_TMP" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."COLLECTION_BATCHES_TMP" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."COLLECTION_BATCHES_TMP" ADD CONSTRAINT "COLLECTION_BATCHES_TMP_PK" PRIMARY KEY ("BATCH_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CISTS_DATA01"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COLLECTION_BATCHES_TMP
--------------------------------------------------------

  ALTER TABLE "CISADM_APPS"."COLLECTION_BATCHES_TMP" ADD CONSTRAINT "COLLECTION_BATCHES_TMP_FK" FOREIGN KEY ("HDR_ID")
	  REFERENCES "CISADM_APPS"."COLLECTION_FILES" ("HDR_ID") ENABLE;
