--------------------------------------------------------
--  DDL for Table PAYERS_TMP
--------------------------------------------------------

  CREATE TABLE "CISADM_APPS"."PAYERS_TMP" 
   (	"PAYER_TYPE" VARCHAR2(10 BYTE), 
	"PAYER_ID" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(64 BYTE), 
	"FIRST_NAME" VARCHAR2(40 BYTE), 
	"MID_NAME" VARCHAR2(40 BYTE), 
	"ADDRESS" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CISTS_DATA01" ;
--------------------------------------------------------
--  DDL for Index PAYERS_TMP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CISADM_APPS"."PAYERS_TMP_PK" ON "CISADM_APPS"."PAYERS_TMP" ("PAYER_TYPE", "PAYER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CISTS_DATA01" ;
--------------------------------------------------------
--  Constraints for Table PAYERS_TMP
--------------------------------------------------------

  ALTER TABLE "CISADM_APPS"."PAYERS_TMP" MODIFY ("PAYER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."PAYERS_TMP" MODIFY ("PAYER_ID" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."PAYERS_TMP" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."PAYERS_TMP" ADD CONSTRAINT "PAYERS_TMP_PK" PRIMARY KEY ("PAYER_TYPE", "PAYER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CISTS_DATA01"  ENABLE;
