--------------------------------------------------------
--  DDL for Table PAYMENT_TRANSACTIONS_TMP
--------------------------------------------------------

  CREATE TABLE "CISADM_APPS"."PAYMENT_TRANSACTIONS_TMP" 
   (	"TRAN_NO" NUMBER, 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"MID_NAME" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"OR_NO" NUMBER(10,0), 
	"OR_DATE" DATE, 
	"OR_STATUS" VARCHAR2(16 BYTE), 
	"REMARKS" VARCHAR2(200 BYTE), 
	"BANK_REF_NO" VARCHAR2(20 BYTE), 
	"BATCH_NO" NUMBER(15,0), 
	"PAYER_ID" VARCHAR2(20 BYTE), 
	"PAYER_TYPE" VARCHAR2(10 BYTE), 
	"POSTED" NUMBER(1,0) DEFAULT 0, 
	"CANCEL_REASON" VARCHAR2(200 BYTE), 
	"OR_COUNT" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CISTS_DATA01" ;
--------------------------------------------------------
--  DDL for Index PAYMENT_TRANSACTIONS_TMP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CISADM_APPS"."PAYMENT_TRANSACTIONS_TMP_PK" ON "CISADM_APPS"."PAYMENT_TRANSACTIONS_TMP" ("TRAN_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CISTS_DATA01" ;
--------------------------------------------------------
--  Constraints for Table PAYMENT_TRANSACTIONS_TMP
--------------------------------------------------------

  ALTER TABLE "CISADM_APPS"."PAYMENT_TRANSACTIONS_TMP" MODIFY ("TRAN_NO" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."PAYMENT_TRANSACTIONS_TMP" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."PAYMENT_TRANSACTIONS_TMP" MODIFY ("OR_NO" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."PAYMENT_TRANSACTIONS_TMP" MODIFY ("OR_DATE" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."PAYMENT_TRANSACTIONS_TMP" MODIFY ("OR_STATUS" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."PAYMENT_TRANSACTIONS_TMP" MODIFY ("BATCH_NO" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."PAYMENT_TRANSACTIONS_TMP" MODIFY ("PAYER_ID" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."PAYMENT_TRANSACTIONS_TMP" MODIFY ("PAYER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CISADM_APPS"."PAYMENT_TRANSACTIONS_TMP" ADD CONSTRAINT "PAYMENT_TRANSACTIONS_TMP_PK" PRIMARY KEY ("TRAN_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CISTS_DATA01"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT_TRANSACTIONS_TMP
--------------------------------------------------------

  ALTER TABLE "CISADM_APPS"."PAYMENT_TRANSACTIONS_TMP" ADD CONSTRAINT "PAYMENT_TRANSACTIONS_TMP_FK" FOREIGN KEY ("BATCH_NO")
	  REFERENCES "CISADM_APPS"."COLLECTION_BATCHES_TMP" ("BATCH_NO") ENABLE;
